DROP TABLE IF EXISTS CURRENCY;

CREATE TABLE CURRENCY (
    CURRENCY_ID INTEGER NOT NULL AUTO_INCREMENT,
    CURRENCY_CODE VARCHAR(128) NOT NULL UNIQUE,
    CHINESE_NAME VARCHAR(128) NOT NULL,
    PRIMARY KEY (CURRENCY_ID)
);